name: Run hypotheses verification tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Sync dependencies
        run: rye sync

      - name: Set up Kaggle authentication
        run: |
          mkdir -p ~/.config/kaggle
          echo "{\"username\": \"${{ secrets.KAGGLE_USERNAME }}\", \"key\": \"${{ secrets.KAGGLE_API_KEY }}\"}" > ~/.config/kaggle/kaggle.json
          chmod 600 ~/.config/kaggle/kaggle.json

      - name: Run hypotheses verification tests
        run: rye run python3 src/app/hypotheses_verification_starter.py

      - name: Run tests
        run: rye run pytest